# GitHub Dependabot config
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"

  # ideally we'd exclude the docs/ dir with something like this, but they don't
  # currently allow multiple sections with the same package-ecosystem.
  # https://github.com/dependabot/dependabot-core/issues/4364
  # - package-ecosystem: "pip"
  #   directory: "/docs"
  #   # disable since we don't build docs in CI
  #   open-pull-requests-limit: 0
