# https://cloud.google.com/appengine/docs/standard/python3/config/appref

# application: granary-demo
# default_expiration: 1h
runtime: python312

# https://cloud.google.com/appengine/docs/standard/python3/runtime#entrypoint_best_practices
# https://docs.gunicorn.org/en/latest/settings.html#timeout
entrypoint: gunicorn --workers 1 --threads 10 --timeout 300 -b :$PORT app:app

# background: https://github.com/snarfed/bridgy/issues/578
automatic_scaling:
  max_idle_instances: 1
  max_concurrent_requests: 10
  max_pending_latency: 2000ms  # default is 30

handlers:
- url: /static
  static_dir: static

- url: /oauth_dropins_static
  static_dir: oauth_dropins_static

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /.well-known/security.txt
  static_files: static/security.txt
  upload: static/security.txt

- url: .*
  script: auto
  secure: always
